providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1707782610'

[variables]
CGO_ENABLED = '0'
NIXPACKS_METADATA = 'go'
PORT = '8090'

[phases.build]
paths = ['/bin','/usr/local/bin']
dependsOn = [
    'install',
    'setup',
]
cmds = ['npm --prefix=./ui run build','go build -o out']
cacheDirectories = ['/root/.cache/go-build']

[phases.install]
dependsOn = ['setup']
cmds = ['go mod download',"npm --prefix=./ui ci"]
cacheDirectories = ['/root/.cache/go-build']

[phases.setup]
nixPkgs = ['nodejs_22','go']
nixOverlays = []
nixpkgsArchive = '1f13eabcd6f5b00fe9de9575ac52c66a0e887ce6'

[start]
cmd = './out serve --http=0.0.0.0:8090 --dir=/data/pb_data '