blank_issues_enabled: false
contact_links:
  - name: "ğŸŒ åŠ å…¥é¢‘é“è®¨è®º"
    about: "åŠ å…¥åˆ°ç”µæŠ¥é¢‘é“å¯»æ±‚æ›´å¤šå¸®åŠ©ã€‚ / Join in our Telegram channel."
    url: "https://t.me/+ZXphsppxUg41YmVl"
  - name: "ğŸ“– å¸¸è§é—®é¢˜"
    about: "è¯·å…ˆé˜…è¯»æ–‡æ¡£ FAQï¼Œå¯èƒ½ä¼šæœ‰ä½ éœ€è¦çš„ç­”æ¡ˆã€‚ / Please take a look to FAQs."
    url: "https://docs.certimate.me/docs/reference/faq"
